=== carrebola/m4/schema/pokemon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="pokemons">
		<xs:annotation>
			<xs:documentation>Esquema para pokemonos</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pokemon" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="altura" type="xs:decimal"/>
							<xs:element name="categoria" type="xs:string"/>
							<xs:element name="habilidades">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="habilidad" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="debilidades">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="debilidad" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="puntosBase">
								<xs:complexType>
									<xs:attribute name="ps" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="defensa" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="velocidad" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ataque" type="xs:integer" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="imagen" type="xs:string" minOccurs="0"/>
							<xs:element name="sexo">
								<xs:complexType>
									<xs:all>
										<xs:element name="masculino" minOccurs="0"/>
										<xs:element name="femenino" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="tipos">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="tipo" maxOccurs="2">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Roca"/>
													<xs:enumeration value="Tierra"/>
													<xs:enumeration value="Fuego"/>
													<xs:enumeration value="Agua"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="nombre" type="xs:string" use="required"/>
						<xs:attribute name="codigo" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="([0-9]{1,4})"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== carrebola/m4/schema/Untitled4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<pokemons xsi:noNamespaceSchemaLocation="pokemon.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<pokemon nombre="String" codigo="^00$">
		<altura>0.0</altura>
		<categoria>String</categoria>
		<habilidades>
			<habilidad>String</habilidad>
			<habilidad>String</habilidad>
			<habilidad>String</habilidad>
		</habilidades>
		<debilidades>
			<debilidad>String</debilidad>
			<debilidad>String</debilidad>
			<debilidad>String</debilidad>
		</debilidades>
		<puntosBase defensa="1" velocidad="1" ps="1"/>
		<imagen>String</imagen>
		<sexo>
			<masculino>text</masculino>
			<femenino>text</femenino>
		</sexo>
		<tipos>
			<tipo>Roca</tipo>
			<tipo>Roca</tipo>
		</tipos>
	</pokemon>
	<pokemon nombre="String" codigo="^00$">
		<altura>0.0</altura>
		<categoria>String</categoria>
		<habilidades>
			<habilidad>String</habilidad>
			<habilidad>String</habilidad>
			<habilidad>String</habilidad>
		</habilidades>
		<debilidades>
			<debilidad>String</debilidad>
			<debilidad>String</debilidad>
			<debilidad>String</debilidad>
		</debilidades>
		<puntosBase defensa="1" velocidad="1" ps="1"/>
		<imagen>String</imagen>
		<sexo>
			<masculino>text</masculino>
			<femenino>text</femenino>
		</sexo>
		<tipos>
			<tipo>Roca</tipo>
			<tipo>Roca</tipo>
		</tipos>
	</pokemon>
	<pokemon nombre="String" codigo="^00$">
		<altura>0.0</altura>
		<categoria>String</categoria>
		<habilidades>
			<habilidad>String</habilidad>
			<habilidad>String</habilidad>
			<habilidad>String</habilidad>
		</habilidades>
		<debilidades>
			<debilidad>String</debilidad>
			<debilidad>String</debilidad>
			<debilidad>String</debilidad>
		</debilidades>
		<puntosBase defensa="1" velocidad="1" ps="1"/>
		<imagen>String</imagen>
		<sexo>
			<masculino>text</masculino>
			<femenino>text</femenino>
		</sexo>
		<tipos>
			<tipo>Roca</tipo>
			<tipo>Roca</tipo>
		</tipos>
	</pokemon>
</pokemons>

=== carrebola/m4/schema/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pokemons xsi:noNamespaceSchemaLocation="pokemon.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<pokemon nombre="Onix" codigo="0019">
		<altura>8.8</altura>
		<categoria>Serpiente Roca</categoria>
		<habilidades>
			<habilidad>Cabeza Roca</habilidad>
			<habilidad>Robustez</habilidad>
		</habilidades>
		<debilidades>
			<debilidad>Agua</debilidad>
			<debilidad>Planta</debilidad>
		</debilidades>
		<puntosBase ps="3" ataque="3" defensa="14"  velocidad="1"/>
		
		<imagen>https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png</imagen>
		<sexo>
				<masculino/>
				<femenino/>
		</sexo>
		<tipos>
				<tipo>Roca</tipo>
				<tipo>Tierra</tipo>
		</tipos>
	</pokemon>
</pokemons>
